package mask

import "strings"

// DigitalOceanToken locates the tokens DigitalOcean issues in the format it
// prefixes: the personal access tokens generated in the control panel (dop_v1_),
// the access tokens an application receives from the OAuth flow (doo_v1_) and
// the refresh tokens handed out beside them (dor_v1_), each with sixty-four
// lowercase hexadecimal characters behind it — seventy-one characters
// altogether.
//
// A token is located wherever it is written, with no word boundary either side,
// and exactly seventy-one characters of it are. So text of that shape is
// redacted whether or not DigitalOcean issued it. A space, an uppercase letter,
// a letter past f or a body of the wrong length ends the reading, so text as it
// is ordinarily written is not affected.
//
// Its name is "digitalocean-token".
func DigitalOceanToken() Pattern { return digitalOceanToken }

// DigitalOcean runs neither the service issuing these nor a generator anybody
// can read, so the format is not read off a published writer as the crates.io,
// Grafana, Vault and RubyGems formats are. What it is read off instead is the
// vendor's own code and the vendor's own reference page, and between them they
// state every part of the grammar but one.
//
// The width comes from doctl, DigitalOcean's CLI, which is published under
// Apache-2.0. Its auth command declares v1TokenLength as 71 and accepts a typed
// token of exactly that many characters opening with do, beside a
// legacyTokenLength of 64 for the format that came before. That is DigitalOcean
// stating the whole width of its own credential in code it ships, and
// seventy-one less the seven characters of a prefix is the sixty-four below.
// The tokens its own tests are written from are the same seventy-one
// characters, and the two the OAuth reference page prints — an access_token and
// the refresh_token beside it — are seventy-one apiece as well. Neither of
// those two is a value: both carry EXAMPLE written over the front of the body,
// which is seven uppercase letters no hexadecimal string holds, and one of them
// carries a y further along. So what the reference page settles is the width
// and nothing else, and a reader auditing this scan against that page finds two
// printed strings it locates nowhere.
// Test_DigitalOceanToken_theShapeTheDocumentationPrints pins that.
//
// The kinds come from DigitalOcean's announcement of the format, which lists
// three patterns of prefixing depending on where a token was generated: doo_v1_
// for tokens generated by applications during the OAuth flow, dop_v1_ for
// personal access tokens generated in the control panel, dor_v1_ for OAuth
// refresh tokens. Each is the two letters of the vendor's initials, one
// character naming the kind and the version the format carries, which is how
// the scan reads them.
//
// What neither source states is the alphabet a body is written in, and it is
// read off the values instead — the only part of this grammar that is. Every
// token DigitalOcean's documentation, its CLI's tests and its Go client's
// README print is lowercase hexadecimal behind the prefix, and the five
// published rulesets reading this format ask for sixty-four of the same
// lowercase class apiece: gitleaks, noseyparker, kingfisher and trufflehog
// spell it [a-f0-9] and osv-scalibr's veles spells the same sixteen characters
// [abcdef0-9]. Where they differ from one another is in what they read the
// class behind — veles reads the personal access token's prefix alone where the
// other four read all three — and in whether a prefix is matched without regard
// to case. Neither the count nor the class is in dispute anywhere.
//
// The three are one pattern rather than three, which is a decision about the
// caller and not about the scanning. None of them is published by design and
// none is the identifier another is kept under: a personal access token and an
// OAuth access token authenticate the same API with the same Bearer header, and
// a refresh token mints fresh ones of the second kind, so a caller with reason
// to redact any of them has the same reason for the rest. Nothing a redactor
// could key on separates them either. What is left is the name, and the term
// below is the one DigitalOcean uses for the whole of what this locates: the
// announcement introduces all three under the new token format, and doctl's
// own count is named for a token rather than for any one kind. Access token
// would be the narrower term — a refresh token is not one, and the vendor
// writes refresh token for the third kind — and a name covering less than a
// pattern locates is a name to change rather than a pattern to split.
//
// A fourth kind exists that this scan does not read. GitHub's secret scanning
// partner list, which DigitalOcean joined when this format shipped, names a
// DigitalOcean System Token beside the three above. DigitalOcean documents no
// such credential, its announcement does not name it, and no published ruleset
// reads one, so there is no prefix to write and nothing to read behind it. A
// kind guessed at would be a candidate opened on text nobody has ever seen; a
// kind stated is a one character change to isDigitalOceanTokenKind below on the
// day the format is published.
// Test_DigitalOceanToken_aKindDigitalOceanNamesNoPrefixFor pins the decision so
// that reading one is a change somebody argues for.
//
// The count is read exactly rather than as a floor, for the reason the AWS,
// GitLab and Google scans give: a run of the alphabet longer than the count is
// not one longer token but a token with something written after it, and only
// the token is redacted. A floor is what a scan reads where its vendor states
// no length; here the length is what the vendor's own validator demands to the
// character.
//
// The alphabet is read as lowercase alone. The whole of the body is one class,
// so widening it to either case would draw in every uppercase digest written
// behind the prefix and buy no case a narrower one loses: were DigitalOcean to
// start writing tokens in some other alphabet, the count would move with it and
// a scan reading sixty-four characters of a wider class would locate the new
// format no better than this one does. noseyparker matches all three prefixes
// without regard to case and gitleaks matches the refresh token's that way,
// which between them locate DOP_V1_ and a lowercase body; that is the shape an
// environment variable's name is written in rather than the shape a token is,
// and reading it would redact the name a caller keeps a log by.
//
// There is no boundary on either side of a match. A word boundary in front
// would drop the whole match rather than trim it wherever a token is written
// against a word character, as DIGITALOCEAN_TOKEN_dop_v1_... is, and one behind
// it would drop a token followed by a character of the body's own alphabet.
// What may stand either side is held back by the character class and the count
// alone. Four of the five rulesets ask for something in front of the match:
// gitleaks, noseyparker and trufflehog open every rule of theirs with \b, and
// kingfisher opens the rule reading the two access token kinds with one and the
// rule reading refresh tokens without.
//
// Declining it costs something here that it does not cost everywhere, and it is
// worth naming both sides. What the demand would buy is a word ending in one of
// the three kinds with a version segment and a digest behind it: doo closes
// voodoo and hoodoo, so voodoo_v1_ and sixty-four hexadecimal characters is a
// candidate this scan locates from its fourth character on, and \b would turn
// it away. What it would cost is the AWS scan's reason — a token written
// straight against a letter or an underscore is dropped whole rather than
// trimmed, and DIGITALOCEAN_TOKEN_dop_v1_... is how a token reaches a log line
// from a shell. A credential left in the output whole is the failure this
// library is for, and a redaction reaching into a name somebody versioned is
// not.
// Test_DigitalOceanToken_aWordEndingInAKind pins the shape that pays for it.
//
// Behind the match the same four ask for something and one of them asks for
// more than a boundary. noseyparker and trufflehog close on \b, kingfisher
// closes the rule reading the two access token kinds on one and the rule
// reading refresh tokens on nothing, and gitleaks closes on a backtick, a
// quote, whitespace, a semicolon, an escaped newline or the end of the input —
// so a token written against a hyphen or a full stop is one gitleaks leaves in
// the text where this pattern redacts it.
//
// The byte the scan searches the input for is the v of the version, four
// characters into every prefix. builtin_scan.go says why a scan searches for
// one byte of its opening rather than for the opening itself, and here the
// choice is settled by the body rather than by prose. A body is sixty-four
// hexadecimal characters, so it carries about four d's and about four 1's and
// never a v: a line of tokens opens one candidate a token under the v and five
// under the d or the 1, which are the other two bytes a prefix carries at a
// fixed index and a body is written with as well. The o stands at a fixed index
// too and no body holds one, but it is a vowel, and the commonest of the four
// over ordinary text by some way. What the choice costs is visible on the line
// these benchmarks are written on, where the vendor's own API path carries a
// version segment: the v stands there twice against the d's once. One line of
// the vendor's URLs is not what a caller's log is, and the count that decides
// this is the one over a body.
//
// The two underscores are rarer still on such a line and are passed over all
// the same. An underscore is what an environment variable, a snake_case name
// and a log field are written with, so a scan anchored on one opens a candidate
// on a great deal of ordinary text to reject it again — and a prefix carrying
// two of them would open two candidates where the v opens one.
//
// The scan advances one byte past the start of a candidate whether that
// candidate became a token or not, which is the default and needs no argument.
// What it finds is narrow and worth stating. A second token can begin at
// exactly one position inside the first: the o of its opening is no hexadecimal
// character, so the two letters a prefix opens with cannot both fall inside a
// body, and no character of a prefix past its first is a d, so no prefix begins
// inside another prefix either. That leaves the last character of the first
// token's body, where a d stands inside and o, a kind and the version are
// written after. The two spans overlap by one character and a Masker resolves
// them into one.
// Test_DigitalOceanToken_aTokenBeginningInsideAnother drives it.
//
// The scan keeps no cursor and needs none: a candidate reads at most
// seventy-one bytes and stops, which bounds what it reads with no state to be
// wrong about — the guarantee a scan reading a body to the end of its run has
// to buy with a run cursor instead, bought here by the count being a count.
//
// What this pattern over-matches on: seventy-one characters of the right shape
// that nobody issued. Seven characters have to be written, two of them
// underscores, then exactly sixty-four lowercase hexadecimal digits with
// nothing between any of them. Base62,
// standard base64 and base32 write no underscore at all, so an identifier, a
// certificate, a PEM body or an embedded image carries no candidate at however
// long it runs. Base64url writes every character of a prefix, and there the
// seven stand about once in four million million characters, with sixty-four
// more having then to fall in sixteen of that alphabet's sixty-four — which is
// four raised to the sixty-fourth against it. Outside an encoding what is left
// is a snake_case name whose segments are spelled do, a kind, v1 and then
// sixty-four hexadecimal characters.
//
// The collision that is reachable is a digest written behind the prefix, and
// this pattern pays for it rather than ruling it out. A SHA-256 is sixty-four
// lowercase hexadecimal characters exactly, which is a body exactly, so
// dop_v1_ and a SHA-256 is a token to this scan. There is nothing left in the
// text to tell the two apart — the vendor's format is that prefix and that many
// of those characters, and no part of it is left over for a digest to fail —
// so a scan declining this would decline every token DigitalOcean issues. An
// MD5 at thirty-two and a SHA-1 at forty are shorter than the count and are
// turned away by it, and so is a bare digest of any length with no prefix in
// front of it. Test_DigitalOceanToken_aDigestBehindThePrefix pins all four.
//
// What reaches a span is never prose. A token holds two underscores in its
// first seven characters and none after, holds no space, and sixty-four
// unbroken hexadecimal characters are longer than anything prose is written in.
//
// The token DigitalOcean issued before this format is not read, and reading it
// is what this package exists not to do. doctl's legacyTokenLength says what
// such a token is: sixty-four characters with no prefix at all, and the values
// beside it in its own tests are lowercase hexadecimal, which is a SHA-256's
// format exactly. A pattern reading that would redact every git object id, every
// digest in every lock file and every cache key a caller passes through. Those
// tokens were not revoked when the prefixes arrived, so they are live and are
// left in the output whole; it is the loose grammar this package declines
// rather than the unlucky one, and
// Test_DigitalOceanToken_theTokenFormatItReplaced pins the decision so that
// reading it is a change somebody argues for rather than one somebody notices
// afterwards.
//
// referenceDigitalOceanToken in builtin_digitalocean_token_test.go keeps the
// grammar as a regular expression, spelling the opening, the three kinds, the
// version, the count and the character class again so that the two are changed
// together, and the fuzz target beside it holds this scan to that expression.
// An expression is affordable here where the crates.io scan's is not: the
// repetition is exact, so the machine an engine builds is read once and stops,
// and the opening is two letters of which the second is written in no body, so
// a run of the body's alphabet holds no candidate at all and an engine searching
// for that literal walks its machine almost nowhere.
var digitalOceanToken = NewPattern("digitalocean-token", func(src string) ([]Span, int) {
	var spans []Span

	// Where the input stops being settled: a piece of a prefix standing at the
	// end of it, or a candidate the end of it cut short. builtin_scan.go says
	// why those are the two.
	retain := digitalOceanTokenTail.start(src)

	for offset := 0; offset < len(src); {
		i := strings.IndexByte(src[offset:], digitalOceanTokenAnchor)
		if i < 0 {
			break
		}
		anchor := offset + i

		// The scan resumes here whether this candidate became a token or not, for the
		// reason the rationale above gives: a token can begin at the last character
		// of the one before it, and a scan consuming its match would step over it.
		offset = anchor + 1

		if anchor < digitalOceanTokenAnchorIndex {
			continue
		}
		start := anchor - digitalOceanTokenAnchorIndex

		// The prefix is read in the order it is written: the opening, the one
		// character naming the kind, then the version. Every anchor the search
		// stops at reaches this line, and the two characters of the opening
		// turn all but a few of them away before the kind is looked at.
		kind := start + len(digitalOceanTokenOpening)
		if !strings.HasPrefix(src[start:], digitalOceanTokenOpening) ||
			!isDigitalOceanTokenKind(src[kind]) ||
			!strings.HasPrefix(src[kind+1:], digitalOceanTokenVersion) {
			continue
		}

		body := start + digitalOceanTokenPrefixChars
		end := start + digitalOceanTokenChars
		if end > len(src) {
			// The input ends inside this candidate, so the count that is the
			// whole of what tells it from anything else written behind the
			// prefix cannot be taken here.
			retain = min(retain, start)
			continue
		}
		if isDigitalOceanTokenBody(src[body:end]) {
			spans = append(spans, Span{Start: start, End: end})
		}
	}
	return spans, retain
})

const (
	// digitalOceanTokenOpening is what every prefix opens with, the two letters
	// of the vendor's initials, and what the scan reads back from its anchor.
	//
	// Its second character is load-bearing: the o is no hexadecimal digit, so
	// the two letters cannot both fall inside a body, which is the whole of the
	// claim that a token begins inside another at one position and no other.
	// Test_digitalOceanTokenOpening holds it there.
	digitalOceanTokenOpening = "do"

	// digitalOceanTokenVersion is what stands behind the character naming the
	// kind, the version the format carries with the underscores either side of
	// it. Both of those are characters no body is written with, so a run of the
	// body's alphabet can hold no prefix and every body begins where such a run
	// begins.
	//
	// That is not what bounds this scan — the count is, as the rationale above
	// says, and the scan would keep no cursor whatever the version closed with.
	// It is what a count relaxed to a floor would have to fall back on, which is
	// why it is stated and held to rather than left to be worked out then.
	digitalOceanTokenVersion = "_v1_"

	// digitalOceanTokenPrefixChars is the whole of a prefix: the opening, the
	// one character naming the kind and the version behind it.
	digitalOceanTokenPrefixChars = len(digitalOceanTokenOpening) + 1 + len(digitalOceanTokenVersion)

	// digitalOceanTokenAnchor is the byte the scan searches the input for and
	// digitalOceanTokenAnchorIndex is where it stands in every prefix, so a
	// candidate begins that many bytes in front of what a search reported.
	// builtin_scan.go says why a scan searches for one byte of its prefix rather
	// than for the prefix itself; the rationale above says what made it this
	// byte, which is that no body carries one. Test_digitalOceanTokenAnchor
	// holds it to standing at this index in every prefix the scan can match.
	digitalOceanTokenAnchor      = 'v'
	digitalOceanTokenAnchorIndex = 4

	// digitalOceanTokenBodyChars is what stands behind a prefix: seventy-one
	// characters, which is doctl's v1TokenLength, less the seven a prefix comes
	// to. Test_digitalOceanTokenChars holds the arithmetic to both numbers.
	digitalOceanTokenBodyChars = 64

	// digitalOceanTokenChars is the whole of a token, the seventy-one
	// characters doctl accepts and the two the OAuth reference page prints are
	// written to.
	digitalOceanTokenChars = digitalOceanTokenPrefixChars + digitalOceanTokenBodyChars
)

// isDigitalOceanTokenKind reports whether c names one of the kinds DigitalOcean
// writes a prefix for: p for a personal access token generated in the control
// panel, o for an access token an application receives from the OAuth flow, r
// for the refresh token handed out beside it.
//
// It is the one declaration saying which kinds there are, and
// digitalOceanTokenPrefixes below reads it rather than writing the prefixes out
// again. builtin_scan.go says why: a table kept beside this is one that can come
// to disagree with it, and what a stream would then do with the kind it had not
// been told about is release the characters a token opens with and redact
// nothing.
func isDigitalOceanTokenKind(c byte) bool {
	return c == 'p' || c == 'o' || c == 'r'
}

// isDigitalOceanTokenBody reports whether s is everything behind the prefix of a
// token: exactly digitalOceanTokenBodyChars characters of the body's alphabet.
//
// It is handed the count as well as the characters so that the two are checked
// in one place rather than the count left to the caller to have cut correctly.
func isDigitalOceanTokenBody(s string) bool {
	if len(s) != digitalOceanTokenBodyChars {
		return false
	}
	for i := range len(s) {
		if !isDigitalOceanTokenBodyByte(s[i]) {
			return false
		}
	}
	return true
}

// isDigitalOceanTokenBodyByte reports whether c is a lowercase hexadecimal
// digit, which is what every token this scan reads is written behind its prefix
// in.
//
// It stays in this file rather than joining the byte tests in builtin_scan.go,
// which hold what more than one scan reads. A hexadecimal class is not one
// class here: a checksum standing behind a body that has already decided a
// match is read in either case, and a whole body is read in lowercase alone,
// each for the reason its own file gives. A shared test named for the class
// rather than for what reads it would have to be one of them, would silently be
// the wrong answer for the other, and would invite the next pattern to read a
// digest with it.
func isDigitalOceanTokenBodyByte(c byte) bool {
	return '0' <= c && c <= '9' || 'a' <= c && c <= 'f'
}

// digitalOceanTokenPrefixes is what a candidate opens with, one entry a kind:
// the opening, the character naming the kind and the version behind it.
//
// The kinds are read out of isDigitalOceanTokenKind rather than written out
// again, so that a kind admitted there is a kind this knows about.
var digitalOceanTokenPrefixes = func() []string {
	var prefixes []string
	for c := range 256 {
		if isDigitalOceanTokenKind(byte(c)) {
			prefixes = append(prefixes, digitalOceanTokenOpening+string(rune(c))+digitalOceanTokenVersion)
		}
	}
	return prefixes
}()

// digitalOceanTokenTail is what the scan settles the tail of its input by.
// prefixTail (builtin_scan.go) says what that is and why it is built once.
var digitalOceanTokenTail = newPrefixTail(digitalOceanTokenPrefixes...)
